//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cansat.Setebos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataLog
    {
        public int Id { get; set; }
        public Nullable<int> ParseId { get; set; }
        public Nullable<double> Temperatura { get; set; }
        public Nullable<double> Altitud { get; set; }
        public Nullable<double> Presion { get; set; }
        public Nullable<double> PresionNivelMar { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitud { get; set; }
        public Nullable<System.DateTime> UTC { get; set; }
        public Nullable<double> GPSAltitud { get; set; }
        public Nullable<double> Satelites { get; set; }
        public Nullable<double> Velocidad { get; set; }
    }
}
