//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cansat.Setebos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        public Flights()
        {
            this.Data = new HashSet<Data>();
        }
    
        public int FlightId { get; set; }
        public bool Active { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Data> Data { get; set; }
    }
}
